apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::491085392395:user/innovatemart-dev-readonly
      username: innovatemart-dev-readonly
      groups:
        - system:masters
